receivers:
  otlp:
    protocols:
      grpc:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      label1: value1

  logging:

  zipkin:
    endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"
    format: proto

  jaeger:
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true
        
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
    # Will encode the whole OTEL message in json
    # This format happen after extracting labels
    format: json
    labels:
      attributes:
        container_name: ""
        source: ""
      resource:
        host.name: "hostname"
        os.description: "os"
        deployment.environment: "env"
        service.name: "service"

  datadog: 
    api:
      site: datadoghq.com
      key: <ADD DD_API_KEY HERE>
          

processors:
  batch:

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, zipkin, jaeger, datadog]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, prometheus]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki]